# Generated by Django 5.0.7 on 2024-09-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=122)),
                ('colortheme', models.CharField(max_length=122)),
                ('gamertag', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
