# Generated by Django 5.0.7 on 2024-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ProductName',
            new_name='color_theme',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='colortheme',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=122),
        ),
    ]
