# Generated by Django 5.0.7 on 2024-09-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_productname_contact_color_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='color_theme',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='gamertag',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='product_name',
            new_name='users_need',
        ),
    ]
